### ISSUE TITLE
Add DNSCrypt support

### ISSUE THREAD

**Issue by fox8091** [tenta-browser/tenta-dns#2]
I'd like to request DNSCrypt support, as I feel that it adds to the security already implemented via DNSSEC and DNS-over-TLS. If you feel this isn't a valid issue, feel free to close.

**Comment by DarthKeizer** [comment]
@fox8091 Great question, hope Tenta will reply.

**Comment by jwriteclub** [comment]
We've generally decided to try and stick with open standards, which is why we've focused on DNS-over-TLS. That having been said, we're working on a couple of blog posts discussing the pros and cons of DNS-over-TLS vs DNSCrypt. When we've got these longer articles done, we'll link to them here, and be happy to engage in a discussion about these options.

**Comment by jwriteclub** [comment]
Here's a [blog post](https://tenta.com/blog/post/2017/12/dns-over-tls-vs-dnscrypt) breaking down some of the differences between DNS-over-TLS and DNSCrypt, and laying out our reasons for this decision.

In short:

> With standardization, operating system manufacturers can provide [DNS-over-TLS] implementations in every platform, and in fact, it's already in progress on Android and we expect more to follow. And thus our most controversial point: If we don't hate DNSCrypt (and we don't), then why not support it? We don't want to expand the use of an older technology when a better standard is within reach. Since DNSCrypt never found significant adoption, let's not stick to it. Let's throw it off and move straight to a future of DNSSEC (although that's another post) and DNS-over-TLS.

As such, we're going to prefer sticking with DNS-over-TLS for our official development efforts. On the flip side, we hope Tenta DNS becomes a popular option with a solid community. If the community submits a DNSCrypt implementation, we will merge it. Even in the case that Tenta DNS does get a DNSCrypt implementation, we think we should define some criteria for when to sunset DNSCrypt elegantly, perhaps as follows:

Proposed Criteria for Sunsetting DNSCrypt
------------------------------------------------------
Each of the following events is worth a certain number of points, sunset DNSCrypt support at 7 points
* Shipping Android Implementation [+2]
* Shipping iOS implementation [+2]
* Well supported iOS third party client [+1]
* Shipping Linux implementation [+1]
* Shipping Windows implementation [+2]
* Well supported Windows third party client [+1]
* Shipping OS X implementation [+2]
* Well supported OS X third party client [+1]
* Built-in support in Chrome [+2]
* Built-in support in Firefox [+2]

We welcome feedback from the community on this decision, and on our proposed criteria if we do receive a DNSCrypt implementation

Editorial Note: We'll leave this issue open for at least 7 days. If we receive significant feedback in that time we'll leave it open for discussion as long as it's relevant.

**Comment by ghost** [comment]
As far as I understand it a service such as [SecureDNS](https://securedns.eu/) offers _DNSCrypt_ **with** _DNS over TLS_

> ✓ No Logging
> ✓ DNSSEC
> ✓ DNSCrypt
> ✓ DNS over TLS 

I'm a non-techie. I've been using DNSCrypt-Proxy for years, nevertheless.
I'm trying to understand that better DNS privacy is or may be making its way.
What I read here is not understandable for a non-techie and moreover seems to concern Android and Linux with Windows users not mentioned.

Practically speaking how would a Windows and DNSCrypt-Proxy user make the switch to what is proposed here as a _better standard_? Is this a work in progress? If so then why has _DNSCrypt.org_ already moved to _DNS Privacy Project_? This is a pain for DNSCrypt-Proxy users, mainly for the update/download of the _**dnscrypt-resolvers.csv**_ file.

Until this _better standard_ be fully available for Windows users and fully explained to non-techies who wish -- and have the right I presume -- to be protected as well, let it be noted that there is a code repository for DNSCrypt-Proxy together with a maintained update of the dnscrypt-resolvers.csv file available at https://github.com/dyne/dnscrypt-proxy

**Comment by jwriteclub** [comment]
@mazesy DNSCrypt and DNS-over-TLS are alternative secure _transport_ for DNS. You use one or the other.

**Comment by jwriteclub** [comment]
As no DNSCrypt implementation for Tenta DNS has been forthcoming, and DNSCrypt is being slowly deprecated, we'll close this issue for now. In the event that someone does want to add a DNSCrypt implementation to Tenta DNS, we'll absolutely take it (subject to code review).

https://twitter.com/jedisct1/status/928942292202860544
https://www.reddit.com/r/linux/comments/7owb1s/psa_dnscrypt_is_now_abandoned/
