### ISSUE TITLE
How can I configure it to proxy another dns and use DNS-over-TLS only?

### ISSUE THREAD

**Issue by kmahyyg** [tenta-browser/tenta-dns#25]
Yes, I want to make it a proxy that can run on the localhost and use DNS-over-TLS only for outbound DNS lookup requests, after get the correct record, return the result to the system.

How should I configure it to do that?

**Comment by mtonsmann** [comment]
Use Stubby: https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Daemon+-+Stubby

I think you will be disappointed though, as I don't think that there is a way to configure it to work with Tenta and TLS
