### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by dklesev** [tenta-browser/tenta-dns#5]
Please add Docker support

**Comment by chaosbunker** [comment]
I would also like to see tenta dns in a docker container

**Comment by julianxhokaxhiu** [comment]
What about docker discovery support? Would be nice to have the possibility for the DNS to listen for Docker events like `start` and `stop` to map docker containers inside the DNS.

This would be extremely useful when using this inside the `docker0` network.

**Comment by jwriteclub** [comment]
So what does docker support look like? Some features, like BGP and dynamic IP link management won't work inside docker. The basic recursive resolver will. So just a docker container that starts the basic recursive resolver?

@julianxhokaxhiu if you'd like to work on support for that, we're open to merging it, _but_, checkout CoreDNS, they have a bunch of features for inside the datacenter.

**Comment by jwriteclub** [comment]
Since #7 is merged, this repo should now be packageable automatically. When #9 is complete, we can use the built in docker support in goreleaser for docker support. This will also require the creation of a few environment variables for the minimal config to run Tenta DNS in docker.

**Comment by jwriteclub** [comment]
As #9 was closed by PR #11 this issue is closed.
